config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :skip => [:sessions, :passwords, :registrations]
  as :user do
    post 'users/sign_in' => 'devise/sessions#create', :as => :user_session
    delete 'users/sign_out' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :password, :password_confirmation, :encrypted_password, :remember_me, :provider, :uid, :oauth_token, :oauth_expires_at

  devise :database_authenticatable, :registerable,
                  :recoverable, :rememberable, :trackable, :validatable,
              :omniauthable, :omniauth_providers => [:reddit]
  has_one :identity, :dependent => :destroy

  validates_presence_of :username

  def self.from_omniauth(auth)
    binding.pry
    identity = Identity.where(provider: auth.provider, uid: auth.uid).first_or_create do |identity|
       if identity.user == nil
         user = User.new
         user.username = auth.info.name
         user.password = Devise.friendly_token[0,20]
       end
       identity.user = user
       identity.access_token = auth['credentials']['token']
       identity.refresh_token = auth['credentials']['refresh_token']
       binding.pry
       identity.expires_at = auth['crendentials']['refresh_token']
       binding.pry
       identity.save
    end
    identity.user
  end







  def email_required?
    false
  end

  def email_changed?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_action :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:username)
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def reddit
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in @user
      redirect_to root_path
    end
  end

  def failure
    redirect_to root_path
  end


#   headers = {"Authorization": "bearer #{token_here}", "User-Agent": "RedditWebDashboard/0.1 by Emilio Corpus"}
#   response = requests.get("https://oauth.reddit.com/api/v1/me", headers=headers)


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    if current_user
      # current_client = RedditClient.new(current_user)
      # binding.pry
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditDashboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'partials/navbar' %>
    <%= yield %>

</body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Reddit Web Dashboard</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if current_user %>
            <%= link_to 'Logout', destroy_user_session_path, :method=>:delete %>
          <% else %>
            <%= link_to "Sign in With Reddit", omniauth_authorize_path(:user, :reddit) %>
          <% end %>
        </li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>